### PR TITLE
fix: namespaces overriding should propagate to dependents if needed

### LINKED ISSUE #1122: `InformerConfiguration` doesn't properly inherit parent configuration if configuration is overridden
The `InformerConfiguration` needs to be notified of the configuration override somehow.

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #1122 
Relies on #1120.

### CODE REVIEW

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java [hunk 1]
```diff
@@ -10,6 +10,10 @@
 @Retention(RetentionPolicy.RUNTIME)
 @Target({ElementType.TYPE})
 public @interface KubernetesDependent {
+  String SAME_AS_PARENT = "JOSDK_SAME_AS_PARENT";
+  String WATCH_ALL_NAMESPACES = "JOSDK_ALL_NAMESPACES";
```
Comment (csviri) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java:14]: This should not be in the `@ControllerConfiguration` ? 
That might be unrelated or not strictly related, but probably we should have just to watch all or selected namespaces. Not sure about the current namespace, but that should be also explicit in case.

**Review by csviri — APPROVED** [review]
Just made one comments, otherwise LGTM

**Comment by csviri** [comment]
The mysql schema test is faling for some reason though.

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java [hunk 2]
```diff
@@ -10,6 +10,10 @@
 @Retention(RetentionPolicy.RUNTIME)
 @Target({ElementType.TYPE})
 public @interface KubernetesDependent {
+  String SAME_AS_PARENT = "JOSDK_SAME_AS_PARENT";
```
Comment (csviri) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java:13]: How is this now used or checked anywhere?

Comment (csviri) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java:13]: Ahh I see, nevermind.

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java (hunk 1 above)
Comment (metacosm) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java:14]: No, this needs to be on this annotation for the dependent to be able to force some configurations which would otherwise be impossible to express.
