### PR TITLE
fix: NPE when no namespace is provided in kube config

### LINKED ISSUE #897: NPE when initializing the operator if there's no explicit namespace set in Kubernetes config

### PR DESCRIPTION
**Pull request by metacosm**
- fix: fail explicitly if current namespace is requested but not available
- fix: retain annotation for reflective access

Fixes #897

### CODE REVIEW

**Review by csviri — APPROVED** [review]
LGTM

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java [hunk 1]
```diff
@@ -67,7 +68,12 @@ static boolean currentNamespaceWatched(Set<String> namespaces) {
         throw new IllegalStateException(
             "Parent ConfigurationService must be set before calling this method");
       }
-      targetNamespaces = Collections.singleton(parent.getClientConfiguration().getNamespace());
+      String namespace = parent.getClientConfiguration().getNamespace();
```
Comment (andreaTP) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: I'm not sure about this change, is possibly going to break user's (especially CIs) environment when a provider doesn't set the default namespace.

I would suggest that if the namespace is `null` you can output a warning message and automatically set it to `default`.

Comment (csviri) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: Btw not sure if this can happen in a real environment (I mean pod), probably just locally, for that purpose might be better to have an exception, so developer won't search for the problem unnecessarily.

Comment (andreaTP) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: A possibility, for the deployment, is to use a [downwardAPI](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api).

Comment (csviri) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: I mean, a default namespace will be always there.

Comment (metacosm) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: Yes, this should only happen when outside of the cluster…

Comment (andreaTP) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: > not sure if this can happen in a real environment

I'm mostly worried about CI ... but, well, an additional command doesn't hurt as well 🤷

Comment (metacosm) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java:71]: Let's see how it goes and maybe revisit if needed?

**Review by andreaTP — APPROVED** [review]
