### PR TITLE
fix: only check for CRD if we're dealing with CustomResources

### LINKED ISSUE #810: CRD checks should be bypassed when reconciling native Kubernetes resources
Right now, the SDK might check that the CRD associated with resources handled by a given `Reconciler` are indeed present on the cluster. This, however, only makes sense if we're reconciling custom resources as it will fail for native Kubernetes resources.

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #810

### CODE REVIEW

**Review by csviri — APPROVED** [review]

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java [hunk 1]
```diff
@@ -167,10 +168,10 @@ public void start() throws OperatorException {
     try {
       // check that the custom resource is known by the cluster if configured that way
       final CustomResourceDefinition crd; // todo: check proper CRD spec version based on config
-      if (configurationService().checkCRDAndValidateLocalModel()) {
-        crd =
-            kubernetesClient.apiextensions().v1().customResourceDefinitions().withName(crdName)
-                .get();
+      if (configurationService().checkCRDAndValidateLocalModel()
```
Comment (csviri) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java:171]: Can we add a unit test?

**Review by csviri — CHANGES_REQUESTED** [review]

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java (hunk 1 above)
Comment (metacosm) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java:171]: Done.

**Review by csviri — APPROVED** [review]
