### PR TITLE
Fix issue with the generation of doneable classes for inner class custom resources

### LINKED ISSUE #249: getCustomResourceDoneableClass doesn't work for inner classes
For example, if you use an inner class for the `CustomResource` implementation for the `ControllerUtilsTest` class, the code won't be able to locate and load the Doneable class appropriately.

@psycho-ir

### PR DESCRIPTION
**Pull request by psycho-ir**
closes #249

### CODE REVIEW

File: operator-framework/src/main/java/io/javaoperatorsdk/operator/CustomResourceToCustomResourceDoneableProvider.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+import java.io.BufferedReader;
+import java.io.IOException;
+import java.io.InputStreamReader;
+import java.net.URL;
+import java.util.*;
+import java.util.stream.Collectors;
+
+
+class CustomResourceToCustomResourceDoneableProvider {
```
Comment (metacosm) [inline operator-framework/src/main/java/io/javaoperatorsdk/operator/CustomResourceToCustomResourceDoneableProvider.java:18]: Can't this and `ClassMappingProvider` somehow be made generic so that they share code?

**Review by metacosm — COMMENTED** [review]
Apart from the `ClassMappingProvider` vs `CustomResourceToCustomResourceDoneableProvider` comment, LGTM.

File: operator-framework/src/main/java/io/javaoperatorsdk/operator/CustomResourceToCustomResourceDoneableProvider.java (hunk 1 above)
Comment (psycho-ir) [reply operator-framework/src/main/java/io/javaoperatorsdk/operator/CustomResourceToCustomResourceDoneableProvider.java:18]: Actually, this class was supposed to be replaced by ClassMappingProvider. 
I think I just missed to remove it, will check.

Comment (psycho-ir) [reply operator-framework/src/main/java/io/javaoperatorsdk/operator/CustomResourceToCustomResourceDoneableProvider.java]: The class was indeed unused, removed it.
